dist: bionic
sudo: false
language: minimal

branches:
  only:
    - master
    - /^v[\d.-]+$/

notifications:
  email: false

before_deploy:
  - curl -L "https://github.com/wiremod/gmad-build/releases/latest/download/gmad_linux" -o "$HOME/gmad_linux"
  - chmod +x "$HOME/gmad_linux"
  - $HOME/gmad_linux create -folder . -out wiremod-extras.gma

deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: EK1zfysVaXMB52mfDlPFwaqM7zGJE/G1iFKyjWMV20GDqZkE9/g+KlwwaRuz7q0NX0KgGuc7dk5j0JQXTg3Z14kUYdIYSq3tDkp0YBeePqVGUgQoA19ZFPlBdZEV0EF3dDHMYmErNYBuCYW7Twrzy++WgzghCcthXaV9jboF5lk=
  file: wiremod-extras.gma
  on:
    repo: wiremod/wire-extras
    tags: true